### ISSUE TITLE
Could load local banner picture?

### ISSUE THREAD

**Issue by CorrectRoadH** [sawhney17/logseq-banners-plugin#12]
Because I feel that the load of banner picture is slow. It may attribute to the my slow computer. But I think accessing local picture is a good idea.

such as 
```
banner:: "../assets/xxx.jpg"
```

**Comment by yoyurec** [comment]
have you tried? )
it's already supported!

![image](https://user-images.githubusercontent.com/137919/177023190-c35f6274-63db-4360-8cc6-f1247e302782.png)

**Comment by CorrectRoadH** [comment]
> have you tried? ) it's already supported!
> 
> ![image](https://user-images.githubusercontent.com/137919/177023190-c35f6274-63db-4360-8cc6-f1247e302782.png)


yes，but it didn't working in my computer

![CleanShot 2022-07-03 at 11 30 22@2x](https://user-images.githubusercontent.com/29306285/177023404-08f70c7c-0747-48d4-93aa-ab467849c0e6.png)

info:
logseq 0.7.5
banner 1.2.3
Solarized Extended Themev1.13.0
macOS 12.4

**Comment by yoyurec** [comment]
looks like there on Mac some different file system. Will try to fix in next version, PR already created

**Comment by CorrectRoadH** [comment]
<img width="546" alt="CleanShot 2022-07-03 at 11 42 19@2x" src="https://user-images.githubusercontent.com/29306285/177023603-b9b50936-7013-441a-8038-14314e3e6187.png">
it may cause by location of graph. this is console of logseq. I try away out of  iCloud.

**Comment by yoyurec** [comment]
`file://` will be changed to Logseq `assets://`... have no possibility to test - i'm on Windows 10

**Comment by yoyurec** [comment]
> Because I feel that the load of banner picture is slow. 

Only custom ones can be slow. Default banners URLs downloaded and cached till Logseq restart\reload.

**Comment by yoyurec** [comment]
BTW, nice theme ahahah 🤣

**Comment by CorrectRoadH** [comment]
I will dive the problem and try to solve it. I is happy to contribute for ecosystem of logseq. 😃

**Comment by CorrectRoadH** [comment]
> BTW, nice theme ahahah rofl

thank for your job. I love this theme very. smiley

**Comment by CorrectRoadH** [comment]
![image](https://user-images.githubusercontent.com/29306285/177024071-25af91ca-d8a6-48a4-9fd9-a638340b61c0.png)
it working well, when logseq run linux. I believe i get it.

**Comment by yoyurec** [comment]
i hope this will fix... https://github.com/sawhney17/logseq-banners-plugin/blob/765d716780ac22e62ca7de197cd48b3b639a4917/src/main.tsx#L331

**Comment by CorrectRoadH** [comment]
> i hope this will fix...
> 
> https://github.com/sawhney17/logseq-banners-plugin/blob/765d716780ac22e62ca7de197cd48b3b639a4917/src/main.tsx#L331

I try also fix it .this is my solution. 
```
      propsBanner = "file://" + graphPath + propsBanner.replace("..", "")
      propsBanner = propsBanner.replace(" ", "%20")
```
now It working well.which solution is suitable and robust?

I try your code later on.

**Comment by CorrectRoadH** [comment]
> propsBanner = "assets://" + graphPath + propsBanner.replace("..", "")
 your solution solve it well!
<img width="369" alt="CleanShot 2022-07-03 at 12 27 34@2x" src="https://user-images.githubusercontent.com/29306285/177024593-53d0bb7c-a74d-473b-9607-7b85cc6772e1.png">
<img width="543" alt="CleanShot 2022-07-03 at 12 27 25@2x" src="https://user-images.githubusercontent.com/29306285/177024594-684379fb-5d60-4393-9c24-b654aca72ea5.png">

**Comment by CorrectRoadH** [comment]
your solution is more elegant.😄

**Comment by yoyurec** [comment]
where `%20` came from?
![image](https://user-images.githubusercontent.com/137919/177024701-eb2d83c4-8d6a-493a-8b2e-b37856919e3f.png)

**Comment by CorrectRoadH** [comment]
> where `%20` came from?
> ![image](https://user-images.githubusercontent.com/137919/177024701-eb2d83c4-8d6a-493a-8b2e-b37856919e3f.png)

oh, this is my negligence. I don't delete my code all. 😂
now it didn't working😖
<img width="1171" alt="CleanShot 2022-07-03 at 12 36 57@2x" src="https://user-images.githubusercontent.com/29306285/177024821-06975fc2-9b60-4a9b-a2bc-877fc64897f1.png">

so we must replace " " to "%20"

**Comment by yoyurec** [comment]
`assets` not fixing issue. 
updated more - https://github.com/sawhney17/logseq-banners-plugin/blob/9af3041cbdd64da14e3490eb2553f84ada0c6b73/src/main.tsx#L331

**Comment by CorrectRoadH** [comment]
> `assets` not fixing the issue. updated - to encode more symbols
> 
> https://github.com/sawhney17/logseq-banners-plugin/blob/9af3041cbdd64da14e3490eb2553f84ada0c6b73/src/main.tsx#L331

<img width="584" alt="CleanShot 2022-07-03 at 12 42 47@2x" src="https://user-images.githubusercontent.com/29306285/177024983-ff8da835-c158-4bbb-a73f-3089519a2ffc.png">

it working now well.

**Comment by yoyurec** [comment]
https://github.com/sawhney17/logseq-banners-plugin/pull/11
Isue can be closed
