### ISSUE TITLE
It's a soooo cool plugin! Could properties be hidden like 'title' ?

### ISSUE THREAD

**Issue by ZackYJz** [sawhney17/logseq-banners-plugin#13]
The 'page-icon' and 'banner' properties is Not very relevant  to the main content,And it's already showing where it should be.
So It doesn't need to be displayed all the time. Could these two be hidden like 'title' ? Only displayed when in edit mode

**Comment by yoyurec** [comment]
* you can use (after new version release) config with the default banner/image for some pages which already have some props. for example `type`...
https://github.com/sawhney17/logseq-banners-plugin/pull/14

* also you can hide props from Logseq  config: https://github.com/logseq/logseq/blob/master/templates/config.edn#L211-L213
but they will not be visible on edit (((
...as workaround you can edit page in external text editor ))
![image](https://user-images.githubusercontent.com/137919/177060657-51dfaa26-7d34-4954-892b-8fa87246eab1.png)

**Comment by yoyurec** [comment]
Or... https://github.com/sawhney17/logseq-banners-plugin/pull/15  )))

**Comment by ZackYJz** [comment]
> Done... #15 )))

It's not working in latest version...

**Comment by yoyurec** [comment]
working on it....

**Comment by vonHartz** [comment]
Any update on this? Just checked with version 3.4.5 and it still does not work for me.
