### ISSUE TITLE
Indent block doesn't show the same banner

### ISSUE THREAD

**Issue by dmytrodubinin** [sawhney17/logseq-banners-plugin#16]
This is the banner of the page:
![image](https://user-images.githubusercontent.com/8066458/177148338-05cff536-15af-454b-a918-e9d1004c08dd.png)

But when I open indent block, its show default banner:
![image](https://user-images.githubusercontent.com/8066458/177148567-b92d11a5-8e6d-40a1-99a8-c58aec4deb5a.png)

**Comment by yoyurec** [comment]
PR created!

**Comment by dmytrodubinin** [comment]
Thanks!
