### ISSUE TITLE
Journals page show banner and icon from previous page

### ISSUE THREAD

**Issue by dmytrodubinin** [sawhney17/logseq-banners-plugin#18]
When I switch from page with banner and go to journals page, journals show me banner from previous page. 
Demo video:

https://user-images.githubusercontent.com/8066458/177198679-5032c673-9efd-497d-91cd-1a376cd17b16.mp4

**Comment by yoyurec** [comment]
Maybe the your journal page content to heavy and the plugin try to render before all data is readable...
Try to set bigger timeout in settings (200, 500...) :
![image](https://user-images.githubusercontent.com/137919/177241347-0b30fcdc-66ec-4012-92a4-ca05dffc995e.png)

**Comment by sawhney17** [comment]
I can replicate this on my machine with a timeout of 2k looks like the journals homepage is not triggering the reload.

**Comment by yoyurec** [comment]
foud, fixing
