### ISSUE TITLE
Cannot resize the right sidebar

### ISSUE THREAD

**Issue by gijigae** [sawhney17/logseq-banners-plugin#20]
I cannot resize the right sidebar with the Banners plugin. Here is a short [demo video](https://www.dropbox.com/s/fweum336a0d3ja6/banners-plugin.gif?raw=1).

**Comment by yoyurec** [comment]
Found! Fixing...

**Comment by yoyurec** [comment]
fixed https://github.com/sawhney17/logseq-banners-plugin/pull/19

**Comment by gijigae** [comment]
Confirmed the fix with the version 1.5.1!
