### ISSUE TITLE
Merge "page-icon" with logseq "icon"

### ISSUE THREAD

**Issue by walsvid** [sawhney17/logseq-banners-plugin#23]
At present, the page of logseq already contains an attribute named `icon::` to set the icon of the page. Is it possible to merge the `page-icon` attribute of this plugin with the `icon`? Maybe in this way, the page does not need to set 2 properties with similar functions.

<img width="1316" alt="2022-07-05 14 56 03" src="https://user-images.githubusercontent.com/17134911/177268526-969cb8ce-9f45-4d54-9b53-d595a21e6dac.png">

**Comment by yoyurec** [comment]
But then you will see 2 smiles icons, no? (((

**Comment by yoyurec** [comment]
oh, i remembered why i stop thinking about it - idea was to rename plugin prop from `page-icon` to `icon`, but then Logseq will add in sidebar titles, maybe useres dont want it.... dunno...

@sawhney17, what do you think?

**Comment by yoyurec** [comment]
PR created https://github.com/sawhney17/logseq-banners-plugin/pull/24

**Comment by sawhney17** [comment]
Ooh, great catch. We should probably update the readme with this.
