### ISSUE TITLE
Set different banner heights for journal pages and common pages and some related suggestions

### ISSUE THREAD

**Issue by AvijeetPrasad** [sawhney17/logseq-banners-plugin#25]
Hi,

Thanks for the great plugin. I have a few requests and suggestions:

- It would be good to have an option to set different banner heights for the journal and common pages. Typically, I would have a larger banner on the journal pages and a slightly smaller one for the common pages to have more screen space.
- It would also be nice to have an option to set the size of the emoji icon or at least it should scale with respect to the banner height. I am finding that on banners with narrower height, the icon is looking quite large.
- The page-icon:: property can be renamed as icon:: property, to be in line with the existing in-built property of Logseq as they have the same functionality.
- When the show default icon is not ticked, even the banner is not visible for common pages. Possibly a bug?

System details:
OS: macOS 12.2.1
Logseq: 0.7.6
Plugin: 1.6.0
Theme: Solarized extended theme 1.14.1

**Comment by pgpais** [comment]
Just to add to this, it could be easier to implement some sort of anchoring of the image so if it is too big, at least the most important part of the image would show. In my case I tried adding an image as a banner but the important part (logo and text) is at the bottom and the image is centered.

**Comment by yoyurec** [comment]
@AvijeetPrasad 

> The page-icon:: property can be renamed as icon:: property, to be in line with the existing in-built property of Logseq as they have the same functionality.

LS `icon` props are already supported in 1.6.0

>When the show default icon is not ticked, even the banner is not visible for common pages. Possibly a bug?

yes, on fixing now

@pgpais 
>  least the most important part of the image would show

there is no AI to detect "most important", so used common centering. Maybe need to add page prop `banner-align:: top | middle(default) | bottom`...

**Comment by sawhney17** [comment]
Should be fixed now.

**Comment by yoyurec** [comment]
PR done - https://github.com/sawhney17/logseq-banners-plugin/pull/29

**Comment by yoyurec** [comment]
> Maybe need to add page prop `banner-align`

not completed yet )

**Comment by yoyurec** [comment]
now yes - https://github.com/sawhney17/logseq-banners-plugin/pull/34 😎
