### ISSUE TITLE
Problems with banners in large window

### ISSUE THREAD

**Issue by ingepettersen** [sawhney17/logseq-banners-plugin#28]
When enlaring the Logseq window with Banners plugin v1.6.1 active, the banner is placed on the left and the text on the right. 

Theme is Solarized Extended. Haven't tried this with other themes. Deactivating banners plugin solves this issue.

Small window:
![image](https://user-images.githubusercontent.com/47382243/178103475-2183fc77-a7cb-4226-888b-0581ca43bb71.png)

Large window:
![image](https://user-images.githubusercontent.com/47382243/178103512-5431a7e4-d775-49c4-aeb5-e998569d99ae.png)

**Comment by yoyurec** [comment]
Its SolExt related bug, so better go to https://github.com/yoyurec/logseq-solarized-extended-theme/issues
BTW, what version are you using? it was fixed in the latest 1.14.2 https://github.com/yoyurec/logseq-solarized-extended-theme/issues/26

**Comment by ingepettersen** [comment]
Confirmed fixed by updating the Solarized Extended theme... I was at 1.14.1.
