### ISSUE TITLE
Logseq shows preview of banner

### ISSUE THREAD

**Issue by yoyurec** [sawhney17/logseq-banners-plugin#3]
Looks like in new versions LS shows image preview without `!` in Markdown link, even without link at all, just by somehow detecting `.jpg`, '.png', etc in URL text ((

Edit mode:
![image](https://user-images.githubusercontent.com/137919/176324426-1f917cc8-8849-469e-9be4-9bf6a6749061.png)

View mode:
![image](https://user-images.githubusercontent.com/137919/176324447-a3bbacd1-0bcd-437d-9866-e7cf0bcb7193.png)

**Comment by sawhney17** [comment]
you can surround the link in quotes. Added this a few versions back

**Comment by yoyurec** [comment]
I think note about this will be useful in readme 🤗

**Comment by sawhney17** [comment]
Great idea.
