### ISSUE TITLE
Set a random banner from API or image urls

### ISSUE THREAD

**Issue by rockbenben** [sawhney17/logseq-banners-plugin#31]
Hi,

Thank you for the plugin you made. The function is great, it makes the logseq page beautiful. 

The default setting can only put one default banner and icon. Could we randomly arrange different covers from the API or multiple image links to increase interest?

**Comment by yoyurec** [comment]
just use random url )

**Comment by Kelvao** [comment]
source.unsplash.com now is deprecated.
