### ISSUE TITLE
Icon not showing up in common page

### ISSUE THREAD

**Issue by helmi-s0** [sawhney17/logseq-banners-plugin#80]
I use debian linux 12. the custom icon is not showing up in common page as well as custom page.
![Screenshot_20230906_075521](https://github.com/yoyurec/logseq-banners-plugin/assets/69077406/f6f7aac0-d309-4019-b301-b44d0e9dc184)

**Comment by VandeeFeng** [comment]
me 2！ i check the css，but it's just disappeared

**Comment by VandeeFeng** [comment]
My console shows that there is a marked problem
